### ISSUE TITLE
14.10, battery level 0 %

### ISSUE THREAD

**Issue by promeneur** [BlissOS/bug_reports#1]
Hello

openSUSE Tumbleweed
QEMU 8.0.3
bliss 14.10

The battery level in a QEMU VM is 0 % in the contrary of android-x86 7.1 r5 or 8.1 r6

This is a problem with an application like WhatsApp, which regularly during conversation warns you it will stop.

Also, I assume this is why opencamera don't want to record any video.

**Comment by hmtheboy154** [comment]
boot with `OMX_NO_YUV420=1`  and `CODEC2_LEVEL=0` and then try to use camera app

Additionally you can set `dumpsys battery set level 100` to fake it to 100

**Comment by promeneur** [comment]
@hmtheboy154 

Thanks

It is too techie for me. Can you describe it step by step what to do ?

**Comment by Xtr126** [comment]
> @hmtheboy154
> 
> Thanks
> 
> It is too techie for me. Can you describe it step by step what to do ?

If you load kernel directly with qemu, you can add kernel cmdline flags to `-append "root=/dev/ram0 quiet SRC=/ OMX_NO_YUV420=1 `
Or edit kernel command line in grub config: https://docs.blissos.org/knowledgebase/troubleshooting/edit-grub-from-bliss-install/

**Comment by promeneur** [comment]
@hmtheboy154 

thanks

And for setting battery level to fake 100 % ?

**Comment by Xtr126** [comment]
> @hmtheboy154
> 
> thanks
> 
> And for setting battery level to fake 100 % ?

It is kind of unexpected that you are a Linux user and run QEMU VMs but don't know how to execute a shell command. `dumpsys battery set level 100` is a command that you can execute using adb or termux with `su`. You could have figured out that by just searching google for `dumpsys battery set level 100`. Grant root access to termux with kernelSU beforehand.

**Comment by promeneur** [comment]
thanks

**Comment by promeneur** [comment]
@hmtheboy154 

I tried in termux "su dumpsys battery set level 100" or "su dumpsys battery set status 1|3".

The level stays at "0 %".

The system says "there a reading problem with the battery measuring tool.
![battery_measure_tool](https://github.com/BlissOS/bug_reports/assets/240424/094edd00-b42d-4225-9edf-6857d69431e8)



Thanks

**Comment by promeneur** [comment]
@hmtheboy154 

>> adding "SRC=/OMX_NO_YUV420=1"

The kernel cmd line is

`kernel /android-2023-07-03/kernel quiet stack_depot_disable=on cgroup_disable=pressure root=/dev/ram0 noexec=off HWC=drm_minigbm GRALLOC=minigbm_arcvm FFMPEG_HWACCEL_DISABLE=1 SRC=/android-2023-07-03`

There is already a SRC option. How to add another SRC option ?

thanks

**Comment by hmtheboy154** [comment]
move to https://github.com/BlissRoms-x86/support/issues for version older than 16
