### ISSUE TITLE
Can't boot Zenith builds on AMD

### ISSUE THREAD

**Issue by ilhan-athn7** [BlissOS/bug_reports#16]
Build : `Bliss-Zenith-v16.9.4-x86_64-OFFICIAL-gapps-20240115.iso`
CPU: `AMD Ryzen 5 5625U with Radeon Graphics`
- I have setup the system through pulling `system`, `kernel` and `initrd` to a folder and adding a menu entry to `Refind` which looks like this;
```
menuentry "BlissOS" {
    icon \EFI\refind\icons\os_mac.png
    volume "archlinux"
    loader /home/BlissOS/kernel
    initrd /home/BlissOS/initrd.img
    options "ro quiet root=/dev/ram0 SRC=/home/BlissOS DATA=data"
}
```
- When I attempt to boot, the blinking cursor got frozen and system does not display anything else.
- If I add argument `nomodeset` to refind config, it can boot normally with software based rendering.

**Comment by hmtheboy154** [comment]
do you feel like it got kernel panic whenever amdgpu got pick ?

**Comment by ilhan-athn7** [comment]
> do you feel like it got kernel panic whenever amdgpu got pick ?

It feels like it hangs on initializing graphics, with different display backlight(brightness), however the display freezes on tty screen.
