### ISSUE TITLE
14.10, Bluetooth 0a5c:21e8 Broadcom Corp. BCM20702A0 Bluetooth 4.0 does not work

### ISSUE THREAD

**Issue by promeneur** [BlissOS/bug_reports#2]
openSUSE Tumbleweed
QEMU 8.0.3
Bliss 14.10

0a5c:21e8 Broadcom Corp. BCM20702A0 Bluetooth 4.0

In the contrary of android-x86 7.1 r5 or 8.1 r6, Bluetooth does not work.

**Comment by promeneur** [comment]
It works well with bliss 15.8.6

**Comment by promeneur** [comment]
Can you back port the Bluetooth modification from 15.8.6 according Bluetooth works in 14.10 ?

Thanks

**Comment by promeneur** [comment]
ASUS USB BT-500 also does not work.

**Comment by hmtheboy154** [comment]
move to https://github.com/BlissRoms-x86/support/issues for version older than 16
