### ISSUE TITLE
Stuck at mesa when building BlissOS 17

### ISSUE THREAD

**Issue by curioxide** [BlissOS/bug_reports#23]
[meson-log.txt](https://github.com/BlissOS/bug_reports/files/14889542/meson-log.txt)
Here's the meson log.
My os is Ubuntu 23.10, this issue also happened before when I was building on 22.04 LTS.

**Comment by electrikjesus** [comment]
Can you please also grab the full build error from /out/build_error or error.log

**Comment by curioxide** [comment]
[error.log](https://github.com/BlissOS/bug_reports/files/14892210/error.log)
[build_error.log](https://github.com/BlissOS/bug_reports/files/14892211/build_error.log)

**Comment by curioxide** [comment]
This may sound dumb but where should I edit if I want to change the `rustc --target` from `x86-linux-android` to `i686-linux-android` when compiling mesa? Since that it appeared at the bottom of the log.

**Comment by hmtheboy154** [comment]
I forgot to add a note because this is just added recently

To prepare building for NVK, which has a Rust-compiler called NAK, I recommend remove any rust toolchain made by distro and straight up install rustup 

https://www.rust-lang.org/tools/install

rustup can give you `i686-linux-android` and `x86_64-linux-android` , use it to build NAK

**Comment by curioxide** [comment]
Weird, I am using rustup and have added `i686-linux-android` and `x86_64-linux-android`. And I can build mesa outside bliss source code.
![Screenshot from 2024-04-09 21-24-58.png](https://github.com/BlissOS/bug_reports/assets/89119074/3790fde8-dfa2-455d-85f3-b90d1edd5fae)

**Comment by curioxide** [comment]
Issue solved, `glodroid/aospext` need to be on `for_nvk` branch but in manifest it is on `main`.

However there comes a new problem says `ld.lld: error: src/nouveau/compiler/libnak_ir_proc.so is incompatible with elf_i386`

I have installed all the dependencies as the manifest Readme and I am back on 22.04lts now.
