### ISSUE TITLE
KernelSU not working...

### ISSUE THREAD

**Issue by ZProLegend007** [BlissOS/bug_reports#25]
![Screenshot_20240525-170153_KernelSU](https://github.com/BlissOS/bug_reports/assets/97338659/71b8ff70-403d-4391-8947-46328208040c)
Screenshot above shows the issue. I've reinstalled. This didn't happen on BlissOS 15. I am using the lastest surface kernel on my sp5. 

It's also worth mentioning the power and volume buttons still don't work without a manual script to fix as mentioned in previous issues. And touchscreen issues on the surface pros.

**Comment by ZProLegend007** [comment]
Any help? I've tested the non surface image on another device and it doesn't have this issue.

**Comment by hmtheboy154** [comment]
Fixed on latest build
