### ISSUE TITLE
Random reboots bliss zenith

### ISSUE THREAD

**Issue by andraluca44zp** [BlissOS/bug_reports#32]
Description
Hi so i played around with this os using a mini pc with n100 and a touchscreen monitor and i had some issue but theres one big problem that makes unusable .
So after random time usually under 1h the bliss os logo appears like its reboot but its faster like coming up from sleep except the logo shows like its starting again and it kills all the apps with it.
So i cant make work more than 1h without os rebooting somehow what could be the issue.
I installed the os on internal nvme efi 2gb 480gb left for os
cpu n100
16gb ddr4
using a uperfect touchscreen monitor connected to it .
Bliss os zenith 16.9.6 generic gapps and foss used both have same issue random reboots.

I tried using older versions of bliss os but the wifi drivers dont work.

it does this with other computer i tested with a n5095 same issue this os its a nightmare i tried 20 different veriosn 80% didnt have enough driver support for the somehow new cpu , on some older version there was no encoder for movies , kernelsu was outdated u couldnt install apps, even on latest zenith version theres issue with wifi , os crashing random times , and with other pc i tested even bluetooth detection has issues .

I just want the os to stop crashing at random times and killing the app its not usable and theres no other versions i can test since theres no driver support.

**Comment by UknowEtheG** [comment]
All of the things you have reported have been submitted in previous issues if you read. 

That said, logs & dmesg?

"It doesn't work" = making us aware of an issue 

providing logs & dmesg = can actually see what's taking place in order to investigate a fix/es

**Comment by andraluca44zp** [comment]
idk how to retrive logs dmesg i could provided if u let me know also how do i change audio device using the terminal alt f1 opens a bliss os terminal but doesnt let me type anything in it and termux deosnt recognize packages

**Comment by andraluca44zp** [comment]
so what happens everything runs great and out of sudden bliss os rebots with welcome bliss logo the pc itself doesnt reboot hibernation its turned off in bios this happens with latest zenith version cant go down since theres missing drivers with older version

**Comment by andraluca44zp** [comment]
just use chrome os guys

**Comment by UknowEtheG** [comment]
how_to_dmesg:

Use KernelSU app to grant su permissions to Termux, then open the built in Termux app, then enter:

system/bin/su 

dmesg > sdcard/dmesg.txt

Then open up the Files app and you can find the dmesg.txt under Termux app files


logcat:

We recommend using LogFox to capture logcat from a booted BlissOS instance.

You can find out more from its official GitHub site as well as available downloads: 

https://github.com/F0x1d/LogFox




The issue you are facing is known. 
The more logs and the dmesg we obtain from different devices the better off we will be in fixing in future builds

**Comment by UknowEtheG** [comment]
> just use chrome os guys

Thanks so much for your contribution

**Comment by gitmanbloggus** [comment]
> just use chrome os guys

your missing out on running android apps at full speed, also chromeos is mentioned only for browsing

**Comment by andraluca44zp** [comment]
thats nonsense apps run much better and stable use brunch+chrome os im using an n100 and everything works i can run 3-4 games at a time too not a single crash with bliss i had crash every 15min on zenith and couldnt even use my full monitor resolution and hz lot of driver werent detected properly

**Comment by andraluca44zp** [comment]
appreciate what ure doing but i tried like 20 os since i couldnt live with bliss os so ill stick with chrome os+brunch best

**Comment by andraluca44zp** [comment]
if  didnt had crashes i probably wouldnt need to change honestly but i do think chrome os to be better for me at least with my hardware

**Comment by gitmanbloggus** [comment]
> if didnt 

> thats nonsense apps run much better and stable use brunch+chrome os im using an n100 and everything works i can run 3-4 games at a time too not a single crash with bliss i had crash every 15min on zenith and couldnt even use my full monitor resolution and hz lot of driver werent detected properly

the use linux + waydroid, MUCH more usable

**Comment by hmtheboy154** [comment]
Close the issue until OP need help again. No info provided & switched to another OS and arguing here is useless
