### ISSUE TITLE
Touchscreen didn’t fully work well

### ISSUE THREAD

**Issue by uOySsElNu** [BlissOS/bug_reports#5]
When I use BlissOS15 or 14 with the Surface-Linux kernel, my Surface Pro 4 does not accurately recognize my sliding and tapping, and this problem is particularly obvious in the left half screen.

**Comment by hmtheboy154** [comment]
BlissOS 14/15 bug reports is here, this is for BlissOS 16 : https://github.com/BlissRoms-x86/support

I just build the surface builds, I can't test these by myself as I don't have the hardware, so you gonna have to go on your own. You can try to file an Issue to iptsd (https://github.com/linux-surface/iptsd/issues) or maybe try to calibrate iptsd here (https://github.com/linux-surface/iptsd/wiki/Calibrating-iptsd)
