### ISSUE TITLE
15.8.6, battery level "?"

### ISSUE THREAD

**Issue by promeneur** [BlissOS/bug_reports#8]
openSUSE Tumbleweed
QEMU 8.1
bliss 15.8.6

Script to launch bliss

`#!/bin/bash

qemu-kvm -enable-kvm
-m 4096 -smp 4 -cpu host
-display gtk,gl=on,zoom-to-fit=off
-device virtio-vga-gl
-device qemu-xhci,p2=5,p3=5,id=xhci
-device usb-ehci,id=ehci
-device usb-kbd
-device usb-mouse
-device usb-tablet
-device usb-host,vendorid=0x046d,productid=0x0825
-device usb-host,bus=xhci.0,port=1,vendorid=0x0b05,productid=0x190e
-device intel-hda
-device hda-duplex,audiodev=snd0
-audiodev pipewire,id=snd0
-boot menu=on
-nic bridge,mac=00:16:3e:4f:90:5a
~/QEMU_VM/Bliss-v15.8.6-x86_64-OFFICIAL-gapps-20230703.img
`

The battery level is "?"

I tried to set it to 100 % without any success

I tried to set the status to "charging" or "charged 100 %" without any success.

**Comment by promeneur** [comment]
Finally, I set the battery level to 100 % with "dumpsys battery set level 100".

But when I restart bliss, then the level is "0 %".

How to set definitively the battery level to "100 %" ?

It is usefull because some app when seeing the "0% then warns they will stop.


Thanks

**Comment by electrikjesus** [comment]
This is a feature only found on our Bass builds so far. https://docs.blissos.org/configuration/configuration-through-command-line-parameters/#battery-stats

**Comment by promeneur** [comment]
I tried this without any success

title BlissOS-15.8.6 2023-07-03 QEMO/KVM
	kernel /android-2023-07-03/kernel quiet stack_depot_disable=on cgroup_disable=pressure root=/dev/ram0 noexec=off video=1680x1050x32 HWC=drm_minigbm GRALLOC=minigbm_arcvm FFMPEG_HWACCEL_DISABLE=1 SRC=/android-2023-07-03 SET_FAKE_BATTERY_LEVEL=100 OMX_NO_YUV420 CODEC2_LEVEL=0

**Comment by promeneur** [comment]
I sent a report here https://github.com/BlissRoms-x86/support/issues/30

I close this issue
