### ISSUE TITLE
15.8.6, each launch, long intensive disk write action

### ISSUE THREAD

**Issue by promeneur** [BlissOS/bug_reports#9]
openSUSE Tumbleweed
QEMU 8.1
bliss 15.8.6

Script to launch bliss

`#!/bin/bash

qemu-kvm -enable-kvm
-m 4096 -smp 4 -cpu host
-display gtk,gl=on,zoom-to-fit=off
-device virtio-vga-gl
-device qemu-xhci,p2=5,p3=5,id=xhci
-device usb-ehci,id=ehci
-device usb-kbd
-device usb-mouse
-device usb-tablet
-device usb-host,vendorid=0x046d,productid=0x0825
-device usb-host,bus=xhci.0,port=1,vendorid=0x0b05,productid=0x190e
-device intel-hda
-device hda-duplex,audiodev=snd0
-audiodev pipewire,id=snd0
-boot menu=on
-nic bridge,mac=00:16:3e:4f:90:5a
~/QEMU_VM/Bliss-v15.8.6-x86_64-OFFICIAL-gapps-20230703.img
`
each time I launch bliss then during about 16 mn, there is intensive disk write.

See the result of iotop

![intense_disk_write](https://github.com/BlissOS/bug_reports/assets/240424/56ab745e-f916-4889-bc2f-b1c9b275ba98)

**Comment by Xtr126** [comment]
Would be useful to monitor the disk I/O load of processes inside the VM, by executing /system_ext/bin/htop

**Comment by promeneur** [comment]
When running "/system_ext/bin/htop" I get

error opening terminal xterm-256color

**Comment by Xtr126** [comment]
> When running "/system_ext/bin/htop" I get
> 
> error opening terminal xterm-256color

Then try running `export TERM=linux`
Not sure where you are running it, but in a root shell from Termux it should work fine.

**Comment by promeneur** [comment]
> > When running "/system_ext/bin/htop" I get
> > error opening terminal xterm-256color
> 
> Then try running `export TERM=linux` Not sure where you are running it, but in a root shell from Termux it should work fine.

I run it in Termux with root right acquired with kernelsu.
![intense_disk_write_2](https://github.com/BlissOS/bug_reports/assets/240424/93d4e55a-7aaa-4c83-9efa-93ad7929a9b2)


Thanks

**Comment by promeneur** [comment]
I try DOS partitioning and GPT partitioning.
Same problem.

ram size for the VM = 8 G
partition size for the VM = 64 G

I need much space for a geographical app.

**Comment by promeneur** [comment]
>> error opening terminal xterm-256color

No more problem since i set all the keyboard to "french"

**Comment by promeneur** [comment]
I send a report here https://github.com/BlissRoms-x86/support/issues/29

I close this issue
